### ISSUE TITLE
切换页面后再切回来图片就一直处于透明状态了

### ISSUE THREAD

**Issue by hubingran** [gs-wenbing/uni-mall#3]
原因应该是加载完之后的图片切换页面后再切回来图片就不会二次加载了,所以导致onImageLoad事件不会触发,添加不上loaded类名,所以图片一直处于透明状态.     但是!!!但是!!!我不知道咋解决啊 请求大佬看看

**Comment by gs-wenbing** [comment]
来回切换时因为需要重新加载数据，所以需要把原来的数据清空，这个bug已经修改

**Comment by xuzigang404** [comment]
感谢大佬
